#include <SFML/Graphics.hpp>
#include <cmath>

#define WINDOW_TITLE "Best Game"
#define FPS 30

#define WINDOW_WIDTH 900
#define WINDOW_HEIGHT 900

#define SPRITE_SIZE 50

#define GRASS_START 10
#define GRASSEATERS_START 12
#define HUNTERS_START 8

#define HUNTERS_LIFE_TIME 700
#define GRASSEATERS_LIFE_TIME 1000
#define GRASSEATERS_HUNGER_DEATH 550
#define HUNTERS_HUNGER_DEATH 130
#define HUNTERS_HUNGER 80
#define GRASSEATERS_HUNGER 300
#define HUNTERS_SEX 220
#define GRASSEATERS_SEX 270

#define HUNTERS_MOVEMENT_SPEED 400
#define GRASSEATERS_MOVEMENT_SPEED 200

#define MIN_RAIN_TIME 100
#define RAIN_SPEED 20
#define RAIN_CONST 300